apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robotics-clusterrole
rules:
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["create"]
