apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: robotics-cb
subjects:
- kind: ServiceAccount
  name: robo-token
  namespace: machine-team1
roleRef:
  kind: ClusterRole
  name: robotics-clusterrole
  apiGroup: rbac.authorization.k8s.io
