apiVersion: v1
kind: PersistentVolume
metadata:
  name: crypto-data
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /srv/crypto-data
    type: DirectoryOrCreate
